# cxxp1
#
Import("env")

env.AppendUnique( CPPPATH=["#cxxp1/include"] )
env['P1_INC_DIR']="#cxxp1/include/p1"

env.SConscript( dirs=[
  "src/util",
  "src/test",
  "src/smalls/common",
  "src/smalls/ast",
  "src/smalls/parser",
  "src/smalls/codegen",
  "src/smalls/test",
])


# Unit tests
tenv = env.Clone()
tenv.AppendUnique(LIBS=['cppunit'])
tenv.Program( target="utest", source=[
  tenv.Object( tenv.Glob("src/utest/*.cpp") ),
  tenv['module']['utest'],
  tenv['module']['p1::util'],
  tenv['module']['p1::smalls::parser'],
  tenv['module']['p1::smalls::ast'],
  tenv['module']['p1::smalls::codegen'],
  tenv['module']['p1::smalls::common'],
])
